### ISSUE TITLE
checkmark visible initially

### ISSUE THREAD

**Issue by kdar** [Polymer/paper-checkbox#21]
When the checkbox first renders, the checkmark is visible:

![image](https://cloud.githubusercontent.com/assets/119919/5908994/537a8808-a57a-11e4-844b-502429d01a08.png)

When you check the checkbox and uncheck it, it is no longer visible:

![image](https://cloud.githubusercontent.com/assets/119919/5909005/77ed058a-a57a-11e4-8161-b530004732cc.png)

This is an issue with backgrounds other than white (I selected the page so you could see it).
The reason is the "hidden" class is only added after it's unchecked.

**Comment by zdarovka** [comment]
At first I was thinking it is feature rather than bug :-D

**Comment by zdarovka** [comment]
I created pull request that repairs this with some additional improvements #22

**Comment by frankiefu** [comment]
fixed by #22

**Comment by ssorallen** [comment]
Pull request #22 has been merged. It fixes this issue.
