### ISSUE TITLE
Why is checkbox different than spec?

### ISSUE THREAD

**Issue by michaelkrog** [Polymer/paper-checkbox#5]
The checkbox(and radioboxes for that matter) looks really sweet. But the material spec has another look:
http://www.google.com/design/spec/components/switches.html#switches-checkbox

Why is that?

The question has been raised during implementation of material design for AngularJS:
https://github.com/angular/material/issues/7

Can you guys elaborate?

**Comment by David-Mulder** [comment]
@frankiefu This is a bit of an odd question, but do you know why the spec was changed? The old checkbox seems to fit the fluid nature of material design far better and we opted to stick around with it in our non-material design web application, so I am just a bit curious.

**Comment by frankiefu** [comment]
The old checkbox was never really in the spec and I implemented it kind of based off on some rough initial design.  I am glad to hear that you like the old one as I also like that better.  I am not really sure how the design team came up with the current design but I will pass your comment to the designers.

**Comment by avinoamr** [comment]
+1. The new spec is kinda disappointing. The old checkbox was so much better looking. @frankiefu  I will appreciate it if you could somehow share the designer's reasoning behind the change.

**Comment by npezza93** [comment]
Is it possible to get the old checkbox back somehow? I tried grabbing an older push but all I get is a green rectangle.

**Comment by ssorallen** [comment]
@npezza93 Try using an older tagged release. Using a commit that wasn't tagged as a release might introduce you to an incomplete checkboc.
